### ISSUE TITLE
Level Progression

### ISSUE THREAD

**Issue by Griffin-Brome** [ubco-video-game-development-club/PrisonBreakRoguelike#25]
Code for going up ladders or stairs whatever to progress to the next level

**Comment by Griffin-Brome** [comment]
- Add stairs object
- Place one (and only one) stairs in the level, inside the "exit" room
- When player collides w/ stairs, generate a new level

**Comment by Griffin-Brome** [comment]
-Need to fix new level generation upon touching stairs object

**Comment by Griffin-Brome** [comment]
-Stairs not appearing for some reason????

**Comment by JadenBalogh** [comment]
> -Stairs not appearing for some reason????

From Discord for reference to anyone reading this thread having the same issue:
> Just got a chance to look at the stairs issue. A couple notes:
>  - When you add a sprite asset to the game, you have to set the Pixels Per Unit to the appropriate size - 64 pixels in our case
>  - On the Stairs.cs script, you have a color field which is overwriting the SpriteRenderer color field. This is probably unnecessary, and also is the reason why the stairs object isn't showing up, because the color is current set to Alpha 0 (aka invisible). Is there a particular reason you added this field?

**Comment by Griffin-Brome** [comment]
> - On the Stairs.cs script, you have a color field which is overwriting the SpriteRenderer color field. This is probably unnecessary, and also is the reason why the stairs object isn't showing up, because the color is current set to Alpha 0 (aka invisible). Is there a particular reason you added this field?

Field has been removed and stairs are now drawn during gameplay

**Comment by Griffin-Brome** [comment]
-Stairs are now working

-When player collides with stairs, a new level will be generated
