### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Griffin-Brome** [ubco-video-game-development-club/PrisonBreakRoguelike#26]
menu screens, displaying item cooldowns and uses, etc

**Comment by Griffin-Brome** [comment]
Title screen is functional but can use polish (not a priority at the moment).

**Comment by Griffin-Brome** [comment]
Currently working on adding a pause menu.

Should contain:

- [x] Button to keep playing
- [x] Button to quit
- [ ] ~~Settings button (features tbd)~~

**Comment by Griffin-Brome** [comment]
Pause menu prototype done, will add settings if needed later on

**Comment by Griffin-Brome** [comment]
Next up is cool down timers

**Comment by JadenBalogh** [comment]
Pushed death screen today. Also added the HUD a while ago.

**Comment by JadenBalogh** [comment]
Updated death and win screens, art for those screens would be ideal.
