### ISSUE TITLE
Player Vision Rework

### ISSUE THREAD

**Issue by Griffin-Brome** [ubco-video-game-development-club/PrisonBreakRoguelike#27]
Light up anything that is on the screen that is within the player's "field of vision" - so they can see infinitely far but not around corners

**Comment by JadenBalogh** [comment]
Currently waiting on feedback from online help for how to implement Unity's new 2D lighting feature which will make this task much easier.

**Comment by JadenBalogh** [comment]
This feature is currently functional, so I'm marking this issue as done. However, please note it's not incredibly clean and may still have performance issues. This will be an ongoing task.
