### ISSUE TITLE
Art Assets

### ISSUE THREAD

**Issue by Griffin-Brome** [ubco-video-game-development-club/PrisonBreakRoguelike#39]
### Art Assets Currently Needed:

- [x] **Floor tiles** - small variety of tiles that are randomly selected from for each tile in each room.
- [ ] **Guards**
  - [ ] idle (should this be an animation?)
  - [ ] walking (do we want a separate "chasing" animation?)
- [ ] **Items** - which would take up one square (but be a little bit smaller), the player still has to be able to see what it is
  - [x] energy drink or any other energy boost-themed item (increases movement speed)
  - [ ] bomb/explosive (for breaking deco)
  - [x] stun gun (some kind of electric taser looking thing)
- [ ] **Deco** - 1 square tables, idk what else here, stuff that takes one square that the player can't walk through.
- [ ] **Player** 
  - [ ] idle (should this be an animation?)
  - [x] walking
  - [ ] using bomb
  - [ ] punch attack? (for breaking deco)
  - [ ] using energy drink
  - [ ] using stun gun

**Comment by JadenBalogh** [comment]
Changed to checklist, checked off floor tiles as we have a good selection of those now.
