### ISSUE TITLE
Game ending

### ISSUE THREAD

**Issue by Griffin-Brome** [ubco-video-game-development-club/PrisonBreakRoguelike#55]
### Cinematic-ish ending for the game in its current state

Some ideas:
- you find a vehicle and drive off
- fly out in helicopter
- kill/attack warden
- front doors are locked, you get arrested and sent back to your cell
- IT WAS ALL A DREAM!!!!???!!! (lol)
- idk feel free to add to this, I'm not a writer

I figure that the game state to trigger this would likely be reaching a certain level, but we could always add something else later on. Right now I will probably set a bool somewhere that says "end state" or something. When that is set to true it would trigger the ending. That way we can just change whatever affects that.

**Comment by JadenBalogh** [comment]
Game ending is now functional (game ends after 3 levels with a basic ending screen). However, we still need story/art to make the ending sequence complete.
